### ISSUE TITLE
Error in compilation

### ISSUE THREAD

**Issue by mikhoul** [Camel-RD/XMLTV-EPG-Viewer#1]
Hi,

I've found tou r project when I was looking for an EPG viewer and I see in the last commits you includedXZ.net so I tried to build the latest "version" and when I try to build the project I receive an error:

> 
> Classes\CProgramData.cs(60,17): error CS1056: Caractère '$' inattendu
>     0 Avertissement(s)
>     1 Erreur(s)

Sorry it's i french and said the "'**$**' is not supposed to be there.

**NOTE:** I have no real clue about what to do to make it work since **I never programmed in C and never compiled a project before today.**

The part of the code that produce the error is a new part from the latest commit in the file: **xmltv/Classes/CProgramData.cs** 

```

  private void DoError(string s, XmlReader xmlReader)
        {
            string lnnr = (xmlReader as IXmlLineInfo).LineNumber.ToString();
            s = $"[{lnnr}]: {s}";
            LogError(s);
            throw new MyException(s);
        }

```

I tried to remove the "**$**" to see what will happen and like I was thinking it produced lot of errors about XZ.net.

Could you help me to correct the **CProgramData.cs** file to have the compilation to work ? 

**Regards** :octocat:

**Comment by Camel-RD** [comment]
Use latest c# compiler (latest Visual Studio).

Added compiled version in releases.
